name: flutter_app
description: A new Flutter application.


version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.3+1
  conditional_builder_null_safety: ^0.0.6
  flutter_bloc: ^6.1.1
  fluttertoast: ^8.2.2
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
